const runStatements = async (dbClient, statements = []) => {
  for (const sql of statements) {
    await dbClient.run(sql);
  }
};

export const applyCoreSchema = async (dbClient) => {
  await runStatements(dbClient, [
    `CREATE TABLE IF NOT EXISTS settings (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      shipping_cost DOUBLE PRECISION DEFAULT 0,
      tax_rate DOUBLE PRECISION DEFAULT 0,
      currency TEXT DEFAULT 'USD',
      free_shipping_threshold DOUBLE PRECISION DEFAULT 0,
      site_name TEXT DEFAULT '',
      site_tagline TEXT DEFAULT '',
      site_description TEXT DEFAULT '',
      contact_email TEXT DEFAULT '',
      contact_phone TEXT DEFAULT '',
      primary_color TEXT DEFAULT '#2563eb',
      footer_text TEXT DEFAULT '',
      invoice_logo TEXT DEFAULT '',
      invoice_notes TEXT DEFAULT '',
      hero_title TEXT DEFAULT '',
      hero_subtitle TEXT DEFAULT '',
      hero_image TEXT DEFAULT '',
      hero_primary_cta_text TEXT DEFAULT '',
      hero_primary_cta_link TEXT DEFAULT '/shop',
      hero_secondary_cta_text TEXT DEFAULT '',
      hero_secondary_cta_link TEXT DEFAULT '/about',
      hero_badge_text TEXT DEFAULT '',
      show_hero_section INTEGER DEFAULT 1,
      show_trust_section INTEGER DEFAULT 1,
      show_categories_section INTEGER DEFAULT 1,
      show_testimonials_section INTEGER DEFAULT 1,
      trust_section_title TEXT DEFAULT '',
      trust_section_subtitle TEXT DEFAULT '',
      categories_section_title TEXT DEFAULT '',
      categories_section_subtitle TEXT DEFAULT '',
      testimonials_section_title TEXT DEFAULT '',
      testimonials_section_subtitle TEXT DEFAULT '',
      about_page_title TEXT DEFAULT '',
      about_page_subtitle TEXT DEFAULT '',
      contact_page_title TEXT DEFAULT '',
      contact_page_subtitle TEXT DEFAULT '',
      show_search_button INTEGER DEFAULT 1,
      show_wishlist_button INTEGER DEFAULT 1,
      show_account_button INTEGER DEFAULT 1,
      home_featured_count INTEGER DEFAULT 4,
      custom_css TEXT DEFAULT '',
      product_highlight_shipping_label TEXT DEFAULT '',
      product_highlight_shipping_value TEXT DEFAULT '',
      product_highlight_warranty_label TEXT DEFAULT '',
      product_highlight_warranty_value TEXT DEFAULT '',
      product_specs_warranty_label TEXT DEFAULT '',
      product_specs_warranty_value TEXT DEFAULT '',
      product_specs_shipping_label TEXT DEFAULT '',
      product_specs_shipping_value TEXT DEFAULT '',
      product_quick_info_title TEXT DEFAULT '',
      product_quick_info_shipping_label TEXT DEFAULT '',
      product_quick_info_shipping_value TEXT DEFAULT '',
      product_quick_info_returns_label TEXT DEFAULT '',
      product_quick_info_returns_value TEXT DEFAULT '',
      product_quick_info_support_label TEXT DEFAULT '',
      product_quick_info_support_value TEXT DEFAULT '',
      product_offer_title TEXT DEFAULT '',
      product_offer_message TEXT DEFAULT '',
      special_offer_enabled INTEGER DEFAULT 0,
      special_offer_product_id INTEGER DEFAULT 0,
      special_offer_start_at TEXT DEFAULT '',
      special_offer_end_at TEXT DEFAULT '',
      special_offer_badge TEXT DEFAULT '',
      special_offer_title TEXT DEFAULT '',
      special_offer_subtitle TEXT DEFAULT '',
      special_offer_cta_text TEXT DEFAULT '',
      special_offer_cta_link TEXT DEFAULT '',
      special_offer_image TEXT DEFAULT '',
      special_offer_discount_percent DOUBLE PRECISION DEFAULT 0,
      special_offer_override_price DOUBLE PRECISION DEFAULT 0,
      special_offers_json TEXT DEFAULT '[]',
      special_offer_show_countdown INTEGER DEFAULT 1,
      special_offer_show_price INTEGER DEFAULT 1,
      social_facebook TEXT DEFAULT '',
      social_instagram TEXT DEFAULT '',
      social_twitter TEXT DEFAULT '',
      social_youtube TEXT DEFAULT '',
      social_linkedin TEXT DEFAULT '',
      social_whatsapp TEXT DEFAULT '',
      home_banners TEXT DEFAULT '[]',
      maintenance_mode INTEGER DEFAULT 0,
      announcement_enabled INTEGER DEFAULT 0,
      announcement_text TEXT DEFAULT '',
      default_language TEXT DEFAULT 'ar',
      currency_symbol TEXT DEFAULT '$',
      enable_dark_mode INTEGER DEFAULT 1,
      dark_mode_default INTEGER DEFAULT 0,
      show_language_toggle INTEGER DEFAULT 1,
      maintenance_message TEXT DEFAULT '',
      show_footer INTEGER DEFAULT 1,
      show_social_links INTEGER DEFAULT 1,
      show_contact_info INTEGER DEFAULT 1,
      show_cart_button INTEGER DEFAULT 1,
      show_admin_link INTEGER DEFAULT 1,
      nav_pin_search_button INTEGER DEFAULT 1,
      nav_pin_wishlist_button INTEGER DEFAULT 1,
      nav_pin_account_button INTEGER DEFAULT 1,
      nav_pin_cart_button INTEGER DEFAULT 1,
      nav_pin_language_toggle INTEGER DEFAULT 0,
      nav_pin_theme_toggle INTEGER DEFAULT 0,
      nav_pin_admin_link INTEGER DEFAULT 0
    )`,

    `CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username TEXT UNIQUE NOT NULL,
      password TEXT NOT NULL,
      role TEXT DEFAULT 'editor',
      full_name TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,

    `CREATE TABLE IF NOT EXISTS media (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      url TEXT NOT NULL,
      filename TEXT,
      mime_type TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,

    `CREATE TABLE IF NOT EXISTS categories (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      image_url TEXT,
      description TEXT
    )`,

    `CREATE TABLE IF NOT EXISTS products (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      description TEXT,
      image_url TEXT,
      hover_image_url TEXT,
      gallery_images_json TEXT DEFAULT '[]',
      base_price DOUBLE PRECISION DEFAULT 0,
      cost_price DOUBLE PRECISION DEFAULT 0,
      sku TEXT,
      stock_quantity INTEGER DEFAULT 0,
      category TEXT,
      has_variants INTEGER DEFAULT 0,
      is_published INTEGER DEFAULT 1,
      specs_json TEXT DEFAULT '[]',
      seo_title TEXT DEFAULT '',
      seo_description TEXT DEFAULT '',
      seo_keywords TEXT DEFAULT '',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,

    `CREATE TABLE IF NOT EXISTS product_variants (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      product_id INTEGER NOT NULL,
      name TEXT NOT NULL,
      price DOUBLE PRECISION NOT NULL,
      cost_price DOUBLE PRECISION DEFAULT 0,
      stock_quantity INTEGER DEFAULT 0,
      sku TEXT,
      FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE
    )`,

    `CREATE TABLE IF NOT EXISTS pages (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      slug TEXT UNIQUE NOT NULL,
      is_published INTEGER DEFAULT 0,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,

    `CREATE TABLE IF NOT EXISTS page_blocks (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      page_id INTEGER NOT NULL,
      type TEXT NOT NULL,
      content TEXT,
      sort_order INTEGER DEFAULT 0,
      FOREIGN KEY(page_id) REFERENCES pages(id) ON DELETE CASCADE
    )`,

    `CREATE TABLE IF NOT EXISTS customers (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email TEXT UNIQUE NOT NULL,
      password TEXT NOT NULL,
      full_name TEXT,
      phone TEXT,
      address TEXT,
      is_active INTEGER DEFAULT 1,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,

    `CREATE TABLE IF NOT EXISTS orders (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      customer_id INTEGER,
      customer_email TEXT,
      customer_name TEXT,
      customer_phone TEXT,
      customer_address TEXT,
      order_notes TEXT,
      subtotal DOUBLE PRECISION DEFAULT 0,
      discount DOUBLE PRECISION DEFAULT 0,
      tax_amount DOUBLE PRECISION DEFAULT 0,
      total_amount DOUBLE PRECISION DEFAULT 0,
      items_json TEXT NOT NULL,
      source TEXT DEFAULT 'online',
      payment_method TEXT DEFAULT 'cod',
      status TEXT DEFAULT 'pending',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE SET NULL
    )`,

    `CREATE TABLE IF NOT EXISTS wishlists (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      customer_id INTEGER NOT NULL,
      product_id INTEGER NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(customer_id, product_id),
      FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE CASCADE,
      FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE
    )`,

    `CREATE TABLE IF NOT EXISTS activity_logs (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER,
      action TEXT,
      entity TEXT,
      entity_id INTEGER,
      details TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
    )`,

    `CREATE TABLE IF NOT EXISTS coupons (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code TEXT UNIQUE NOT NULL,
      type TEXT DEFAULT 'fixed',
      value DOUBLE PRECISION NOT NULL,
      is_active INTEGER DEFAULT 1,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,

    `CREATE TABLE IF NOT EXISTS product_reviews (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      product_id INTEGER NOT NULL,
      name TEXT,
      rating INTEGER DEFAULT 5,
      title TEXT,
      body TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE
    )`
  ]);
};
